package Calculator;


/**
* Calculator/Calc.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calc.idl
* Wednesday, October 21, 2015 8:35:38 PM PDT
*/

public interface Calc extends CalcOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Calc
