package Calculator;


/**
* Calculator/CalcOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calc.idl
* Wednesday, October 21, 2015 8:35:38 PM PDT
*/

public interface CalcOperations 
{
  int calculate (int opcode, int op1, int op2);
  void exit ();
} // interface CalcOperations
