package Calculator;


/**
* Calculator/CalcOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calc.idl
* Friday, March 21, 2025 2:09:02 PM IST
*/

public interface CalcOperations 
{
  int calculate (int opcode, int op1, int op2);
  void exit ();
} // interface CalcOperations
