package FileTransferApp;

/**
* FileTransferApp/FileTransferHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/FileTransfer.idl
* Friday, March 21, 2025 3:09:31 PM IST
*/

public final class FileTransferHolder implements org.omg.CORBA.portable.Streamable
{
  public FileTransferApp.FileTransfer value = null;

  public FileTransferHolder ()
  {
  }

  public FileTransferHolder (FileTransferApp.FileTransfer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FileTransferApp.FileTransferHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FileTransferApp.FileTransferHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FileTransferApp.FileTransferHelper.type ();
  }

}
