package FileTransferApp;


/**
* FileTransferApp/FileDataHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/FileTransfer.idl
* Friday, March 21, 2025 3:09:31 PM IST
*/

public final class FileDataHolder implements org.omg.CORBA.portable.Streamable
{
  public byte value[] = null;

  public FileDataHolder ()
  {
  }

  public FileDataHolder (byte[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FileTransferApp.FileDataHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FileTransferApp.FileDataHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FileTransferApp.FileDataHelper.type ();
  }

}
