package FileTransferApp;


/**
* FileTransferApp/FileTransfer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/FileTransfer.idl
* Friday, March 21, 2025 3:09:31 PM IST
*/

public interface FileTransfer extends FileTransferOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FileTransfer
